refactor: Upgrade to dev version again
* There is some issues [^1] in Beta. Besides, the "dev" version was working good, and the bugs fixed faster.
* Lock Twig to 3.14.*, because the newer Twig development version triggers the "Warning: Undefined variable $_vO" issue. I'm not sure why this occurs, and I cannot reproduce it in a clean project.

[^1] Uncaught Error: Too few arguments to function PHPStan\PhpDocParser\Parser\ConstExprParser::__construct(), 0 passed in /vendor/symfony/property-info/Extractor/PhpStanExtractor.php on line 82 and exactly 1 expected ["exception" => ArgumentCountError { …}]